# Generated by Django 4.0.4 on 2022-04-25 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, null=True)),
                ('modified_at', models.DateField(auto_now=True, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('quentity', models.IntegerField(default=1)),
                ('purchase', models.BooleanField(default=False)),
                ('item_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, null=True)),
                ('modified_at', models.DateField(auto_now=True, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('orderedOrNot', models.BooleanField(default=False)),
                ('paymentID', models.CharField(blank=True, max_length=264, null=True)),
                ('orderID', models.CharField(blank=True, max_length=264, null=True)),
                ('orderItems', models.ManyToManyField(to='OrderApp.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
